name = "SlyFoxesV2"
author = "GibkiJan"
version = "0.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a289f358bda717097fd67a65a1e19ac7ffd96d401048aa2632a0ff0d67533bc0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
