name = "SlyFoxesV2"
author = "GibkiJan"
version = "0.8.2F"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9166072cc3c5be35f52e32a09750924e8d19f2d1f6d7049b38eae3b2ae48a2c7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
