name = "SlyFoxesV2"
author = "GibkiJan"
version = "0.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8755336bd5df6babee4801eff4974bf7451b6d679c8c2665a10d8ca95e56a480"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
